### ISSUE TITLE
value值为null时有空指针异常

### ISSUE THREAD

**Issue by xiawei520** [colincatsu/fast-object-diff#11]
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "oldValue" is null

**Comment by colincatsu** [comment]
> java.lang.NullPointerException: Cannot invoke "Object.toString()" because "oldValue" is null

能给个DEMO吗

**Comment by xiawei520** [comment]
您好：
&nbsp; &nbsp; &nbsp;您代码中有2处toString()调用有空指针异常，下图是我修改的地方。在&nbsp;AbstractObjectDiff 类中。












&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "colincatsu/fast-object-diff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [colincatsu/fast-object-diff] value值为null时有空指针异常 (Issue #11)





  
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "oldValue" is null
  
能给个DEMO吗

**Comment by colincatsu** [comment]
@xiawei520 
用email回复再github上看不到图片...

**Comment by colincatsu** [comment]
@xiawei520 看最新版本是否修复了您的问题 版本1.5

**Comment by xiawei520** [comment]
应该是修复了，我看最新代码里面，出问题的2处代码已做了非空判断
