### ISSUE TITLE
oldValue= null， newValue =一个对象且这个对象所有的字段都是null，或newValue= null， oldValue=一个对象且这个对象所有的字段都是null

### ISSUE THREAD

**Issue by xiawei520** [colincatsu/fast-object-diff#12]
oldValue= null， newValue =一个对象且这个对象所有的字段都是null，或newValue= null， oldValue=一个对象且这个对象所有的字段都是null, 对比会认为这2个不相等。其实这2种情况都是没有变化。但是工具认为是变化了。

**Comment by colincatsu** [comment]
@xiawei520 可以给出一个例子，我复现一下

**Comment by colincatsu** [comment]
@xiawei520 而且我感觉你说的这个不算是问题哈，毕竟对象new出来了

**Comment by xiawei520** [comment]
纯java来说确实不是一个对象，但从业务上来说其实不管null或者""都是无变化的。demo 不太好给 ，我的场景是前端传的JSON转成了java对象，然后对比从数据库查出来的对象。我在AbstractObjectDiff 42行修改新增了代码判断逻辑 
if (sourceObject == null && targetObject == null) {
            return null;
        } else if ((sourceObject == null && ReflectUtils.areFieldsNull(targetObject))
                || (sourceObject != null && ReflectUtils.areFieldsNull(sourceObject) && targetObject == null)) {
            return null;
        }

**Comment by xiawei520** [comment]
可能我写的还没覆盖全

**Comment by colincatsu** [comment]
> 纯java来说确实不是一个对象，但从业务上来说其实不管null或者""都是无变化的。demo 不太好给 ，我的场景是前端传的JSON转成了java对象，然后对比从数据库查出来的对象。我在AbstractObjectDiff 42行修改新增了代码判断逻辑 if (sourceObject == null && targetObject == null) { return null; } else if ((sourceObject == null && ReflectUtils.areFieldsNull(targetObject)) || (sourceObject != null && ReflectUtils.areFieldsNull(sourceObject) && targetObject == null)) { return null; }

我先关了，这个大多数可能遇不到这个场景
