### ISSUE TITLE
简单对象list不能对比

### ISSUE THREAD

**Issue by lmandlyp163** [colincatsu/fast-object-diff#2]
demo1 demo1 = new demo1();
        demo1.setName("name1");
        demo1.setDesc("desc1");
        demo1.setValue(1);
        demo1.setList(Lists.newArrayList(1l,2l));

        demo1 demo2 = new demo1();
        demo2.setName("name2");
        demo2.setDesc("desc2");
        demo2.setValue(2);
        demo2.setList(Lists.newArrayList(2l,3l));

        List<DiffWapper> diffWappers = AbstractObjectDiff.generateDiff(demo1, demo2);
        System.out.println(JsonUtils.encode(diffWappers));

        System.out.println("==========");

        String s = ChineseObjectDiff.genChineseDiffStr(demo1, demo2);

        System.out.println(s);

    @DiffLog(name = "名称")
    private String name;

    @DiffLog(name = "描述")
    private String desc;

    @DiffLog(name = "值")
    private Integer value;

    @DiffLog(name = "list")
    private List<Long> list;

**Comment by lmandlyp163** [comment]
「名称」由[name1]修改为[name2]
「描述」由[desc1]修改为[desc2]
「值」由[1]修改为[2]

**Comment by colincatsu** [comment]
@lmandlyp163 暂不支持该功能，后期考虑迭代进去
