### ISSUE TITLE
AbstractObjectDiff不能对比Short和Byte类型

### ISSUE THREAD

**Issue by luminglong** [colincatsu/fast-object-diff#4]
![image](https://user-images.githubusercontent.com/39085653/150053249-a7524310-adb8-45d3-8c17-9512c9f78a6e.png)

**Comment by colincatsu** [comment]
是，我觉得意义不大，就没处理

**Comment by colincatsu** [comment]
不太符合该工具目标

**Comment by luminglong** [comment]
那能实现下Short和Byte类型的对比吗？ 然后升级下版本。 我现在在项目中用到了你这个包，然后不支持这两种类型，导致处理起来非常麻烦。

**Comment by colincatsu** [comment]
@luminglong Byte，Short对比你需要什么样的效果，我周末抽空加一下吧

**Comment by colincatsu** [comment]
@luminglong 代码已经更新，稍后我回家换电脑更新一下中央仓库

**Comment by colincatsu** [comment]
@luminglong 已经同步到中央仓库，稍后再尝试即可
