### ISSUE TITLE
java.util.Date cannot be cast to java.sql.Timestamp

### ISSUE THREAD

**Issue by sanlion** [colincatsu/fast-object-diff#8]
https://github.com/colincatsu/fast-object-diff/blob/19c4c2ad8e3a89fcdcb315d4367c88b5e8702d8d/src/main/java/com/fastobject/diff/AbstractObjectDiff.java#L297

**Comment by colincatsu** [comment]
fixed

**Comment by colincatsu** [comment]
已经发布到中央仓库

**Comment by colincatsu** [comment]
@sanlion  请更新到 1.3版本即可
